[tasks.install-commitlint.mac]
script = [
    """
    brew install npm
  	yarn install
  	yarn husky install
    """,
]
script_runner = "@shell"

[tasks.install-commitlint.windows]
script = [
    """
    echo "WIP"
    """,
]
script_runner = "@duckscript"

[tasks.install-commitlint.linux]
script = [
    """
    if command -v apt &> /dev/null
    then
      echo "Installing node.js and yarn (sudo apt install nodejs yarn)"
      sudo apt install nodejs yarn
    else
    echo "Installing node.js and yarn (sudo pacman -S nodejs yarn)"
      sudo pacman -S nodejs yarn
    fi

    yarn install
    yarn husky install
    """,
]
script_runner = "@shell"
