export default {
  viewId: '04acbc17-2265-4e4d-ac80-392bdc81379f',
  rootId: '3EzeCrtxlh',
  nodeMap: {
    '692ooXzoV-': {
      id: '692ooXzoV-',
      type: 'todo_list',
      parent: '3EzeCrtxlh',
      children: '4yIcpjxFTQ',
      data: { checked: false },
      externalId: '9L10h3UZ7J',
      externalType: 'text',
    },
    gCjs671FiD: {
      id: 'gCjs671FiD',
      type: 'paragraph',
      parent: '3EzeCrtxlh',
      children: 'Bj4M6midh3',
      data: {},
      externalId: 'uGR_eATq2B',
      externalType: 'text',
    },
    whGVOpFJzA: {
      id: 'whGVOpFJzA',
      type: 'code',
      parent: '3EzeCrtxlh',
      children: 'eYqZSaUSrF',
      data: { language: 'rust' },
      externalId: '2H8dnFhOsJ',
      externalType: 'text',
    },
    PeUTr8lpaW: {
      id: 'PeUTr8lpaW',
      type: 'divider',
      parent: '3EzeCrtxlh',
      children: '7gXZ4anHxc',
      data: {},
      externalId: '',
      externalType: '',
    },
    aRUJ8rTJR9: {
      id: 'aRUJ8rTJR9',
      type: 'quote',
      parent: '3EzeCrtxlh',
      children: '877leNxAdX',
      data: {},
      externalId: 'Qdn9CIuCJb',
      externalType: 'text',
    },
    '5OZNiernqA': {
      id: '5OZNiernqA',
      type: 'paragraph',
      parent: '3EzeCrtxlh',
      children: 'rnWU0OMG2D',
      data: {},
      externalId: '7szeShePbX',
      externalType: 'text',
    },
    '6okS7LcJz6': {
      id: '6okS7LcJz6',
      type: 'paragraph',
      parent: '3EzeCrtxlh',
      children: 'o2VwjuyMqD',
      data: {},
      externalId: 'T7KYfpQzkC',
      externalType: 'text',
    },
    '2qonPRrNTO': {
      id: '2qonPRrNTO',
      type: 'heading',
      parent: '3EzeCrtxlh',
      children: 'EwyNm_pVG3',
      data: { level: 1 },
      externalId: 'zatA8Lta9U',
      externalType: 'text',
    },
    G6SPYNOXyd: {
      id: 'G6SPYNOXyd',
      type: 'heading',
      parent: '3EzeCrtxlh',
      children: 'dMAT_mdB3t',
      data: { level: 2 },
      externalId: 'EZJU9Ks-XL',
      externalType: 'text',
    },
    'i-7TRjZWn4': {
      id: 'i-7TRjZWn4',
      type: 'todo_list',
      parent: '3EzeCrtxlh',
      children: '3NsAmPWBLT',
      data: { checked: true },
      externalId: 'rG9KOmfyQc',
      externalType: 'text',
    },
    mAce5pJ5iN: {
      id: 'mAce5pJ5iN',
      type: 'paragraph',
      parent: '3EzeCrtxlh',
      children: 'PavtRGeb_I',
      data: {},
      externalId: 'UUBk3lnHDj',
      externalType: 'text',
    },
    ViWXVLgaux: {
      id: 'ViWXVLgaux',
      type: 'numbered_list',
      parent: '3EzeCrtxlh',
      children: 'osPbZZroOQ',
      data: {},
      externalId: 'OkO9CIoWYX',
      externalType: 'text',
    },
    VrW0GWtvmq: {
      id: 'VrW0GWtvmq',
      type: 'todo_list',
      parent: '3EzeCrtxlh',
      children: 'hFX8bE3MQ6',
      data: { checked: false },
      externalId: 'wBzhBx7bcM',
      externalType: 'text',
    },
    YzM4q9vJgy: {
      id: 'YzM4q9vJgy',
      type: 'paragraph',
      parent: '3EzeCrtxlh',
      children: 'mlDk334eJ5',
      data: {},
      externalId: 'wIXo3cMKpn',
      externalType: 'text',
    },
    okBQecghDx: {
      id: 'okBQecghDx',
      type: 'todo_list',
      parent: '3EzeCrtxlh',
      children: 'r7U-ocUQEj',
      data: { checked: false },
      externalId: '8T-1vemF9G',
      externalType: 'text',
    },
    qJcR2SnePa: {
      id: 'qJcR2SnePa',
      type: 'callout',
      parent: '3EzeCrtxlh',
      children: 'X8-C5rdFkI',
      data: { icon: '🥰' },
      externalId: 'o3mqcqjEvX',
      externalType: 'text',
    },
    q8trFTc21J: {
      id: 'q8trFTc21J',
      type: 'numbered_list',
      parent: '3EzeCrtxlh',
      children: 'Ye_KrA1Zqb',
      data: {},
      externalId: 'E-XQYK1KGP',
      externalType: 'text',
    },
    '-7trMtJMEt': {
      id: '-7trMtJMEt',
      type: 'numbered_list',
      parent: '3EzeCrtxlh',
      children: '5-RQuN9654',
      data: {},
      externalId: 'meKXZh3E_1',
      externalType: 'text',
    },
    Fn4KACkt1i: {
      id: 'Fn4KACkt1i',
      type: 'todo_list',
      parent: '3EzeCrtxlh',
      children: 'MM6vCgc7RC',
      data: { checked: false },
      externalId: 'v0XWYu0w3F',
      externalType: 'text',
    },
    TTU0eUzM4G: {
      id: 'TTU0eUzM4G',
      type: 'paragraph',
      parent: '3EzeCrtxlh',
      children: 'Jo1ix-lCgZ',
      data: {},
      externalId: 'IRpzcwVaU4',
      externalType: 'text',
    },
    '6QZZccBfnT': {
      id: '6QZZccBfnT',
      type: 'heading',
      parent: '3EzeCrtxlh',
      children: 'bdI2gAQB-G',
      data: { level: 2 },
      externalId: 'J-oMw2g2_D',
      externalType: 'text',
    },
    sZT5qbJvLX: {
      id: 'sZT5qbJvLX',
      type: 'paragraph',
      parent: '3EzeCrtxlh',
      children: 'yR1_d6lPtR',
      data: {},
      externalId: 'anA255zYMV',
      externalType: 'text',
    },
    '3EzeCrtxlh': {
      id: '3EzeCrtxlh',
      type: 'page',
      parent: '',
      children: 'ChrjyUcqp5',
      data: {},
      externalId: 'bGaty5Tv88',
      externalType: 'text',
    },
    'b3G76VM-nh': {
      id: 'b3G76VM-nh',
      type: 'heading',
      parent: '3EzeCrtxlh',
      children: '7PDV2Ev8pz',
      data: { level: 2 },
      externalId: 'baM4S6ohnQ',
      externalType: 'text',
    },
    CxPil0324P: {
      id: 'CxPil0324P',
      type: 'todo_list',
      parent: '3EzeCrtxlh',
      children: 'qJkq_FYLux',
      data: { checked: false },
      externalId: 'LGUrob79hg',
      externalType: 'text',
    },
  },
  childrenMap: {
    '-7trMtJMEt': [],
    okBQecghDx: [],
    PeUTr8lpaW: [],
    '6QZZccBfnT': [],
    aRUJ8rTJR9: [],
    G6SPYNOXyd: [],
    VrW0GWtvmq: [],
    'i-7TRjZWn4': [],
    '6okS7LcJz6': [],
    Fn4KACkt1i: [],
    qJcR2SnePa: [],
    sZT5qbJvLX: [],
    '2qonPRrNTO': [],
    CxPil0324P: [],
    YzM4q9vJgy: [],
    mAce5pJ5iN: [],
    gCjs671FiD: [],
    q8trFTc21J: [],
    whGVOpFJzA: [],
    '5OZNiernqA': [],
    'b3G76VM-nh': [],
    TTU0eUzM4G: [],
    '3EzeCrtxlh': [
      '2qonPRrNTO',
      'b3G76VM-nh',
      'CxPil0324P',
      'Fn4KACkt1i',
      'okBQecghDx',
      'VrW0GWtvmq',
      'i-7TRjZWn4',
      '692ooXzoV-',
      'sZT5qbJvLX',
      'PeUTr8lpaW',
      'YzM4q9vJgy',
      'G6SPYNOXyd',
      '-7trMtJMEt',
      'q8trFTc21J',
      'ViWXVLgaux',
      'whGVOpFJzA',
      'mAce5pJ5iN',
      '6QZZccBfnT',
      'aRUJ8rTJR9',
      'gCjs671FiD',
      'qJcR2SnePa',
      '5OZNiernqA',
      'TTU0eUzM4G',
      '6okS7LcJz6',
    ],
    ViWXVLgaux: [],
    '692ooXzoV-': [],
  },
  relativeMap: {
    '4yIcpjxFTQ': '692ooXzoV-',
    Bj4M6midh3: 'gCjs671FiD',
    eYqZSaUSrF: 'whGVOpFJzA',
    '7gXZ4anHxc': 'PeUTr8lpaW',
    '877leNxAdX': 'aRUJ8rTJR9',
    rnWU0OMG2D: '5OZNiernqA',
    o2VwjuyMqD: '6okS7LcJz6',
    EwyNm_pVG3: '2qonPRrNTO',
    dMAT_mdB3t: 'G6SPYNOXyd',
    '3NsAmPWBLT': 'i-7TRjZWn4',
    PavtRGeb_I: 'mAce5pJ5iN',
    osPbZZroOQ: 'ViWXVLgaux',
    hFX8bE3MQ6: 'VrW0GWtvmq',
    mlDk334eJ5: 'YzM4q9vJgy',
    'r7U-ocUQEj': 'okBQecghDx',
    'X8-C5rdFkI': 'qJcR2SnePa',
    Ye_KrA1Zqb: 'q8trFTc21J',
    '5-RQuN9654': '-7trMtJMEt',
    MM6vCgc7RC: 'Fn4KACkt1i',
    'Jo1ix-lCgZ': 'TTU0eUzM4G',
    'bdI2gAQB-G': '6QZZccBfnT',
    yR1_d6lPtR: 'sZT5qbJvLX',
    ChrjyUcqp5: '3EzeCrtxlh',
    '7PDV2Ev8pz': 'b3G76VM-nh',
    qJkq_FYLux: 'CxPil0324P',
  },
  deltaMap: {
    gCjs671FiD: [],
    G6SPYNOXyd: [{ insert: 'Keyboard shortcuts, markdown, and code block' }],
    VrW0GWtvmq: [
      { insert: 'Type ' },
      { insert: '/', attributes: { code: true } },
      { insert: ' followed by ' },
      { insert: '/bullet', attributes: { code: true } },
      { insert: ' or ' },
      { insert: '/num', attributes: { code: true } },
      { insert: ' to create a list.', attributes: { code: false } },
    ],
    '-7trMtJMEt': [
      { insert: 'Keyboard shortcuts ' },
      {
        insert: 'guide',
        attributes: { href: 'https://appflowy.gitbook.io/docs/essential-documentation/shortcuts' },
      },
    ],
    okBQecghDx: [
      { insert: 'As soon as you type ' },
      { insert: '/', attributes: { font_color: '0xff00b5ff', code: true } },
      { insert: ' a menu will pop up. Select ' },
      { insert: 'different types', attributes: { bg_color: '0x4d9c27b0' } },
      { insert: ' of content blocks you can add.' },
    ],
    qJcR2SnePa: [
      { insert: '\nLike AppFlowy? Follow us:\n' },
      { insert: 'GitHub', attributes: { href: 'https://github.com/AppFlowy-IO/AppFlowy' } },
      { insert: '\n' },
      { insert: 'Twitter', attributes: { href: 'https://twitter.com/appflowy' } },
      { insert: ': @appflowy\n' },
      { insert: 'Newsletter', attributes: { href: 'https://blog-appflowy.ghost.io/' } },
      { insert: '\n' },
    ],
    whGVOpFJzA: [
      {
        insert:
          '// This is the main function.\nfn main() {\n    // Print text to the console.\n    println!("Hello World!");\n}',
      },
    ],
    YzM4q9vJgy: [],
    '692ooXzoV-': [
      { insert: 'Click ' },
      { insert: '+', attributes: { code: true } },
      { insert: ' next to any page title in the sidebar to ' },
      { insert: 'quickly', attributes: { font_color: '0xff8427e0' } },
      { insert: ' add a new subpage, ' },
      { insert: 'Document', attributes: { code: true } },
      { insert: ', ', attributes: { code: false } },
      { insert: 'Grid', attributes: { code: true } },
      { insert: ', or ', attributes: { code: false } },
      { insert: 'Kanban Board', attributes: { code: true } },
      { insert: '.', attributes: { code: false } },
    ],
    q8trFTc21J: [
      { insert: 'Markdown ' },
      {
        insert: 'reference',
        attributes: { href: 'https://appflowy.gitbook.io/docs/essential-documentation/markdown' },
      },
    ],
    ViWXVLgaux: [
      { insert: 'Type ' },
      { insert: '/code', attributes: { code: true } },
      { insert: ' to insert a code block', attributes: { code: false } },
    ],
    sZT5qbJvLX: [],
    '6QZZccBfnT': [{ insert: 'Have a question❓' }],
    '5OZNiernqA': [],
    '6okS7LcJz6': [],
    mAce5pJ5iN: [],
    aRUJ8rTJR9: [
      { insert: 'Click ' },
      { insert: '?', attributes: { code: true } },
      { insert: ' at the bottom right for help and support.' },
    ],
    Fn4KACkt1i: [
      { insert: 'Highlight ', attributes: { bg_color: '0x4dffeb3b' } },
      { insert: 'any text, and use the editing menu to ' },
      { insert: 'style', attributes: { italic: true } },
      { insert: ' ' },
      { insert: 'your', attributes: { bold: true } },
      { insert: ' ' },
      { insert: 'writing', attributes: { underline: true } },
      { insert: ' ' },
      { insert: 'however', attributes: { code: true } },
      { insert: ' you ' },
      { insert: 'like.', attributes: { strikethrough: true } },
    ],
    '3EzeCrtxlh': [],
    '2qonPRrNTO': [{ insert: 'Welcome to AppFlowy!' }],
    'b3G76VM-nh': [{ insert: 'Here are the basics' }],
    TTU0eUzM4G: [],
    CxPil0324P: [{ insert: 'Click anywhere and just start typing.' }],
    'i-7TRjZWn4': [
      { insert: 'Click ' },
      { insert: '+ New Page ', attributes: { code: true } },
      { insert: 'button at the bottom of your sidebar to add a new page.' },
    ],
  },
  externalIdMap: {
    '9L10h3UZ7J': '692ooXzoV-',
    uGR_eATq2B: 'gCjs671FiD',
    '2H8dnFhOsJ': 'whGVOpFJzA',
    Qdn9CIuCJb: 'aRUJ8rTJR9',
    '7szeShePbX': '5OZNiernqA',
    T7KYfpQzkC: '6okS7LcJz6',
    zatA8Lta9U: '2qonPRrNTO',
    'EZJU9Ks-XL': 'G6SPYNOXyd',
    rG9KOmfyQc: 'i-7TRjZWn4',
    UUBk3lnHDj: 'mAce5pJ5iN',
    OkO9CIoWYX: 'ViWXVLgaux',
    wBzhBx7bcM: 'VrW0GWtvmq',
    wIXo3cMKpn: 'YzM4q9vJgy',
    '8T-1vemF9G': 'okBQecghDx',
    o3mqcqjEvX: 'qJcR2SnePa',
    'E-XQYK1KGP': 'q8trFTc21J',
    meKXZh3E_1: '-7trMtJMEt',
    v0XWYu0w3F: 'Fn4KACkt1i',
    IRpzcwVaU4: 'TTU0eUzM4G',
    'J-oMw2g2_D': '6QZZccBfnT',
    anA255zYMV: 'sZT5qbJvLX',
    bGaty5Tv88: '3EzeCrtxlh',
    baM4S6ohnQ: 'b3G76VM-nh',
    LGUrob79hg: 'CxPil0324P',
  },
};
