#!/usr/bin/env bash
if [ -e /usr/local/bin/appflowy ]; then
    echo "Symlink already exists, skipping."
else
    echo "Creating Symlink in /usr/local/bin/appflowy"
    ln -s /opt/appflowy/appflowy /usr/local/bin/appflowy
fi
