export const Keyboard = {
  codes: {
    BACKSPACE: 8,
    TAB: 9,
    ENTER: 13,
    ESCAPE: 27,
    SPACE: 32,
    LEFT: 37,
    UP: 38,
    RIGHT: 39,
    DOWN: 40,
    DELETE: 46,
  },
  keys: {
    BACKSPACE: 'Backspace',
    TAB: 'Tab',
    ENTER: 'Enter',
    ESCAPE: 'Escape',
    SPACE: ' ',
    LEFT: 'ArrowLeft',
    UP: 'ArrowUp',
    RIGHT: 'ArrowRight',
    DOWN: 'ArrowDown',
    DELETE: 'Delete',
    SHIFT_ENTER: 'Shift+Enter',
    SHIFT_TAB: 'Shift+Tab',
    Slash: '/',
    Space: ' ',
    Reduce: '-',
    BackQuote: '`',
    FORMAT: {
      BOLD: 'Mod+b',
      ITALIC: 'Mod+i',
      UNDERLINE: 'Mod+u',
      STRIKE: 'Mod+Shift+s',
      CODE: 'Mod+Shift+c',
    },
    COPY: 'Mod+c',
    CUT: 'Mod+x',
    PASTE: 'Mod+v',
  },
};
