import 'package:appflowy/workspace/application/settings/appearance/appearance_cubit.dart';
import 'package:flowy_svg/flowy_svg.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class ScalableFlowySvg extends StatelessWidget {
  const ScalableFlowySvg(
    this.svg, {
    super.key,
    this.size,
    this.color,
    this.blendMode = BlendMode.srcIn,
  });

  /// The data for the flowy svg. Will be generated by the generator in this
  /// package within bin/flowy_svg.dart
  final FlowySvgData svg;

  /// The size of the svg
  final Size? size;

  /// The color of the svg.
  ///
  /// This property will not be applied to the underlying svg widget if the
  /// blend mode is null, but the blend mode defaults to [BlendMode.srcIn]
  /// if it is not explicitly set to null.
  final Color? color;

  /// The blend mode applied to the svg.
  ///
  /// If the blend mode is null then the icon color will not be applied.
  /// Set both the icon color and blendMode in order to apply color to the
  /// svg widget.
  final BlendMode? blendMode;

  @override
  Widget build(BuildContext context) {
    return Transform.scale(
      scale:
          context.watch<AppearanceSettingsCubit>().state.fontIconsSizeFactor +
              1, //delete 1 later
      child: FlowySvg(
        svg,
        size: size,
        color: color,
        blendMode: blendMode,
      ),
    );
  }
}
