import { DocumentState } from '$app/interfaces/document';

export const mockDocument = {
  nodes: {
    wh475aelU_: {
      id: 'wh475aelU_',
      type: 'numbered_list',
      parent: 'ifF_PvQeOu',
      children: 'VcfuvGuodm',
      data: {},
      externalId: 'sUF-3L5JHd',
      externalType: 'text',
    },
    pYV_AGVqEE: {
      id: 'pYV_AGVqEE',
      type: 'todo_list',
      parent: 'ifF_PvQeOu',
      children: 'e6ByZ0nZk9',
      data: { checked: false },
      externalId: 'F3zvDsXHha',
      externalType: 'text',
    },
    '0whp025621': {
      id: '0whp025621',
      type: 'callout',
      parent: 'ifF_PvQeOu',
      children: 'b5ypKcGf5_',
      data: { bgColor: '#F0F0F0', icon: '🥰' },
      externalId: 'P_ODpxtY-S',
      externalType: 'text',
    },
    d4Qo2OFOpX: {
      id: 'd4Qo2OFOpX',
      type: 'paragraph',
      parent: 'ifF_PvQeOu',
      children: '2lNOUVOJJ5',
      data: {},
      externalId: 'QT_VkSHge-',
      externalType: 'text',
    },
    tLi0Tg4dBc: {
      id: 'tLi0Tg4dBc',
      type: 'paragraph',
      parent: 'ifF_PvQeOu',
      children: 'rgDc-GrgOa',
      data: {},
      externalId: '7FQuBVPxeZ',
      externalType: 'text',
    },
    '-sili1kmaR': {
      id: '-sili1kmaR',
      type: 'todo_list',
      parent: 'ifF_PvQeOu',
      children: 'mAxPJngROh',
      data: { checked: false },
      externalId: 'VGLCGgx_rk',
      externalType: 'text',
    },
    '5I64JF3Hzw': {
      id: '5I64JF3Hzw',
      type: 'numbered_list',
      parent: 'ifF_PvQeOu',
      children: 'TzJU1gv2PE',
      data: {},
      externalId: 'zYOHSlXpWE',
      externalType: 'text',
    },
    'eqf0luv-Fy': {
      id: 'eqf0luv-Fy',
      type: 'todo_list',
      parent: 'ifF_PvQeOu',
      children: 'oxKR2cHeeH',
      data: {
        checked: false,
      },
      externalId: '6BnmM6ZkJV',
      externalType: 'text',
    },
    ZMPoVs7lC4: {
      id: 'ZMPoVs7lC4',
      type: 'numbered_list',
      parent: 'ifF_PvQeOu',
      children: 'jwB_QmOn21',
      data: {},
      externalId: 'qIDnwwdSQF',
      externalType: 'text',
    },
    'PM-4wkNVlu': {
      id: 'PM-4wkNVlu',
      type: 'paragraph',
      parent: 'ifF_PvQeOu',
      children: 'HdHqxm7-e-',
      data: {},
      externalId: 'lPI1KU7usc',
      externalType: 'text',
    },
    '5qS3sKv9C2': {
      id: '5qS3sKv9C2',
      type: 'heading',
      parent: 'ifF_PvQeOu',
      children: 'LaCFrFbNeA',
      data: { level: 2 },
      externalId: 'fy82xqO08a',
      externalType: 'text',
    },
    tEGSjQM2LP: {
      id: 'tEGSjQM2LP',
      type: 'todo_list',
      parent: 'ifF_PvQeOu',
      children: 'G_zBND8YZl',
      data: { checked: true },
      externalId: 'xWJGGIB-fp',
      externalType: 'text',
    },
    IteP77UNrr: {
      id: 'IteP77UNrr',
      type: 'divider',
      parent: 'ifF_PvQeOu',
      children: '8ZAdHr4H4J',
      data: {},
      externalId: '',
      externalType: '',
    },
    vMc1WwxjJu: {
      id: 'vMc1WwxjJu',
      type: 'quote',
      parent: 'ifF_PvQeOu',
      children: 'zWkL_b8_Mi',
      data: {},
      externalId: 'oOxRotTYg2',
      externalType: 'text',
    },
    gtYcSzwLYw: {
      id: 'gtYcSzwLYw',
      type: 'heading',
      parent: 'ifF_PvQeOu',
      children: 'WhIA288H8O',
      data: { level: 1 },
      externalId: 'KbkL-wXQrN',
      externalType: 'text',
    },
    jk7YrtfAgz: {
      id: 'jk7YrtfAgz',
      type: 'paragraph',
      parent: 'ifF_PvQeOu',
      children: 'KIO68twg3J',
      data: {},
      externalId: 'b3BIaLzS_o',
      externalType: 'text',
    },
    jAl6GnPNB_: {
      id: 'jAl6GnPNB_',
      type: 'todo_list',
      parent: 'ifF_PvQeOu',
      children: 'HR3s1f_gpD',
      data: { checked: false },
      externalId: 'qiW6xN-o5Q',
      externalType: 'text',
    },
    NFtEOGjXEm: {
      id: 'NFtEOGjXEm',
      type: 'paragraph',
      parent: 'ifF_PvQeOu',
      children: 'kDx1WbW6ni',
      data: {},
      externalId: 'r19i_oNV3O',
      externalType: 'text',
    },
    '4f6_TWg8x5': {
      id: '4f6_TWg8x5',
      type: 'paragraph',
      parent: 'ifF_PvQeOu',
      children: 'RGXTAjco5O',
      data: {},
      externalId: 'pf1dV9EJer',
      externalType: 'text',
    },
    xFhJgOxACc: {
      id: 'xFhJgOxACc',
      type: 'heading',
      parent: 'ifF_PvQeOu',
      children: 'CMqq7y9JTX',
      data: { level: 2 },
      externalId: 'b3mbfhloLa',
      externalType: 'text',
    },
    'kih-t9tRZr': {
      id: 'kih-t9tRZr',
      type: 'code',
      parent: 'ifF_PvQeOu',
      children: 'fnWMHsa5if',
      data: { language: 'rust' },
      externalId: 'HBZkdYM6Ka',
      externalType: 'text',
    },
    ifF_PvQeOu: {
      id: 'ifF_PvQeOu',
      type: 'page',
      parent: '',
      children: '5_bawmri6x',
      data: {},
      externalId: 'm_SX-ck0GL',
      externalType: 'text',
    },
    'YsJ-DVO-sC': {
      id: 'YsJ-DVO-sC',
      type: 'heading',
      parent: 'ifF_PvQeOu',
      children: 'PM5MctaruD',
      data: { level: 2 },
      externalId: 'QHPzz4O1mV',
      externalType: 'text',
    },
    JcIU0PjpyD: {
      id: 'JcIU0PjpyD',
      type: 'todo_list',
      parent: 'ifF_PvQeOu',
      children: 'xcYFnxMXai',
      data: { checked: false },
      externalId: 'g4WQvF8doI',
      externalType: 'text',
    },
    Oi2cxSuUls: {
      id: 'Oi2cxSuUls',
      type: 'paragraph',
      parent: 'ifF_PvQeOu',
      children: 'NI4TCeq2Lv',
      data: {},
      externalId: 'D27H4Hf9re',
      externalType: 'text',
    },
  },
  children: {
    xcYFnxMXai: [],
    '5_bawmri6x': [
      'gtYcSzwLYw',
      'YsJ-DVO-sC',
      'jAl6GnPNB_',
      '-sili1kmaR',
      'pYV_AGVqEE',
      'JcIU0PjpyD',
      'tEGSjQM2LP',
      'eqf0luv-Fy',
      '4f6_TWg8x5',
      'IteP77UNrr',
      'PM-4wkNVlu',
      '5qS3sKv9C2',
      '5I64JF3Hzw',
      'wh475aelU_',
      'ZMPoVs7lC4',
      'kih-t9tRZr',
      'Oi2cxSuUls',
      'xFhJgOxACc',
      'vMc1WwxjJu',
      'd4Qo2OFOpX',
      '0whp025621',
      'tLi0Tg4dBc',
      'jk7YrtfAgz',
      'NFtEOGjXEm',
    ],
    'rgDc-GrgOa': [],
    jwB_QmOn21: [],
    b5ypKcGf5_: [],
    LaCFrFbNeA: [],
    '8ZAdHr4H4J': [],
    'HdHqxm7-e-': [],
    G_zBND8YZl: [],
    CMqq7y9JTX: [],
    WhIA288H8O: [],
    HR3s1f_gpD: [],
    zWkL_b8_Mi: [],
    KIO68twg3J: [],
    oxKR2cHeeH: [],
    fnWMHsa5if: [],
    kDx1WbW6ni: [],
    '2lNOUVOJJ5': [],
    PM5MctaruD: [],
    TzJU1gv2PE: [],
    RGXTAjco5O: [],
    e6ByZ0nZk9: [],
    VcfuvGuodm: [],
    mAxPJngROh: [],
    NI4TCeq2Lv: [],
  },
  deltaMap: {
    VGLCGgx_rk:
      '[{"insert":"Highlight ","attributes":{"bg_color":"0x4dffeb3b"}},{"insert":"any text, and use the editing menu to "},{"insert":"style","attributes":{"italic":true}},{"insert":" "},{"insert":"your","attributes":{"bold":true}},{"insert":" "},{"insert":"writing","attributes":{"underline":true}},{"insert":" "},{"insert":"however","attributes":{"code":true}},{"insert":" you "},{"insert":"like.","attributes":{"strikethrough":true}}]',
    '6BnmM6ZkJV':
      '[{"insert":"Click "},{"insert":"+","attributes":{"code":true}},{"insert":" next to any page title in the sidebar to "},{"insert":"quickly","attributes":{"font_color":"0xff8427e0"}},{"insert":" add a new subpage, "},{"insert":"Document","attributes":{"code":true}},{"insert":", ","attributes":{"code":false}},{"insert":"Grid","attributes":{"code":true}},{"insert":", or ","attributes":{"code":false}},{"insert":"Kanban Board","attributes":{"code":true}},{"insert":".","attributes":{"code":false}}]',
    g4WQvF8doI:
      '[{"insert":"Type "},{"insert":"/","attributes":{"code":true}},{"insert":" followed by "},{"insert":"/bullet","attributes":{"code":true}},{"insert":" or "},{"insert":"/num","attributes":{"code":true}},{"insert":" to create a list.","attributes":{"code":false}}]',
    HBZkdYM6Ka:
      '[{"insert":"// This is the main function.\\nfn main() {\\n    // Print text to the console.\\n    println!(\\"Hello World!\\");\\n}"}]',
    'qiW6xN-o5Q': '[{"insert":"Click anywhere and just start typing."}]',
    'KbkL-wXQrN': '[{"insert":"Welcome to AppFlowy!"}]',
    lPI1KU7usc: '[]',
    D27H4Hf9re: '[]',
    oOxRotTYg2:
      '[{"insert":"Click "},{"insert":"?","attributes":{"code":true}},{"insert":" at the bottom right for help and support."}]',
    'P_ODpxtY-S':
      '[{"insert":"\\nLike AppFlowy? Follow us:\\n"},{"insert":"GitHub","attributes":{"href":"https://github.com/AppFlowy-IO/AppFlowy"}},{"insert":"\\n"},{"insert":"Twitter","attributes":{"href":"https://twitter.com/appflowy"}},{"insert":": @appflowy\\n"},{"insert":"Newsletter","attributes":{"href":"https://blog-appflowy.ghost.io/"}},{"insert":"\\n"}]',
    F3zvDsXHha:
      '[{"insert":"As soon as you type "},{"insert":"/","attributes":{"code":true,"font_color":"0xff00b5ff"}},{"insert":" a menu will pop up. Select "},{"insert":"different types","attributes":{"bg_color":"0x4d9c27b0"}},{"insert":" of content blocks you can add."}]',
    fy82xqO08a: '[{"insert":"Keyboard shortcuts, markdown, and code block"}]',
    'sUF-3L5JHd':
      '[{"insert":"Markdown "},{"insert":"reference","attributes":{"href":"https://appflowy.gitbook.io/docs/essential-documentation/markdown"}}]',
    r19i_oNV3O: '[]',
    'm_SX-ck0GL': '[]',
    b3mbfhloLa: '[{"insert":"Have a question❓"}]',
    'xWJGGIB-fp':
      '[{"insert":"Click "},{"insert":"+ New Page ","attributes":{"code":true}},{"insert":"button at the bottom of your sidebar to add a new page."}]',
    'QT_VkSHge-': '[]',
    zYOHSlXpWE:
      '[{"insert":"Keyboard shortcuts "},{"insert":"guide","attributes":{"href":"https://appflowy.gitbook.io/docs/essential-documentation/shortcuts"}}]',
    b3BIaLzS_o: '[]',
    '7FQuBVPxeZ': '[]',
    pf1dV9EJer: '[]',
    QHPzz4O1mV: '[{"insert":"Here are the basics"}]',
    qIDnwwdSQF:
      '[{"insert":"Type "},{"insert":"/code","attributes":{"code":true}},{"insert":" to insert a code block","attributes":{"code":false}}]',
  },
} as DocumentState;
