name: Translation Notify
on:
  push:
    branches: [ main ]
    paths:
      - "frontend/appflowy_flutter/assets/translations/en.json"

jobs:
  Discord-Notify:
    runs-on: ubuntu-latest
    steps:
      - uses: Ilshidur/action-discord@d2594079a10f1d6739ee50a2471f0ca57418b554 # master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            @appflowytranslators English UI strings has been updated.
            Link to changes: ${{github.event.compare}}
